### ISSUE TITLE
"Lightbulb" icon

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#11]
The meaning of the Lightbulb icon on the status screen is not clear.

If the unit is in DMX only mode, then the unit should always be sending DMX.
If the unit is sending ethernet packets, it makes more sense that this might be useful feedback, but in this case, the dim vs bright outline of the icon is not clear enough to the user that one state is "on" and the other is "off".
This needs to be Yellow vs black, or filled vs hollow.

Perhaps there is a different icon for network sending vs dmx.

But beyond the actual icon, I am still not sure what the purpose of this feedback is in a normal usage setup.
At least I'm not sure what it means on the taskbar.

**Comment by HakanL** [comment]
I added it more for me to see the output status (if it's sending on the network or not), but valid feedback, I'll think if there's really any purpose to keep it.
