### ISSUE TITLE
Record DMX input

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#12]
We discussed this on the phone, but the ability to record actual DMX input data will, *I think*, be important for a larger application base where only one or two universes of data are being used.

I'm not sure if there would be a way to set both to record and also be able to monitor the playback, but this is something that should be explored.
Perhaps you record 1 stream and then a 2nd stream and you can sync them on playback.

I do think that the record mode needs to pass the DMX through, so you can see what it's doing while you are recording.
Or you need to sell a "Y" cable, so the lights are doing the same thing while the device is recording. In this way, both ports could be recording.

**Comment by HakanL** [comment]
It will be a later enhancement to support DMX input, I need to write the DMX-board processor firmware to support this. DMX monitor when recording from network should be straightforward, see #2.

**Comment by HakanL** [comment]
This has been implemented now.
