### ISSUE TITLE
Software Update Bug issue 2

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#14]
When the screen is in left in the Software update page for an extended period, the system freezes and does not respond.

After some time, the system has rebooted.

**Comment by HakanL** [comment]
Did this happen when the network got unplugged?

**Comment by VividRGBLighting** [comment]
No, it happened while it was still plugged in.

**Comment by HakanL** [comment]
I think it happened because it got disconnected at some point, which flooded the logs with errors and then the watchdog probably restarted it. I believe it's fixed now, my unit here can now run disconnected.
