### ISSUE TITLE
Add IP address to About page

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#15]
For easy access to information, the About page should report the current IP configuration.
It should also report the software revision - which I think it does, but it doesn't report it in the same name/format as the software revisions update page. - specifically, it is missing the date info - I am assuming here that most users would not be updating the firmware multiple times in a day, so date would be the most basic info here.

Perhaps, if it is saved somewhere, would also be the date the firmware was updated.

**Comment by HakanL** [comment]
The IP address is already there, but the display of the firmware could be better.

**Comment by VividRGBLighting** [comment]
There is no IP address displayed on the about screen on my unit.

**Comment by HakanL** [comment]
There is a bug (or missing feature, depending on how you see it) in the UI library that doesn't show the scrollbar until you hover over the controls with a mouse. Without a mouse it just never shows. I'm working on a fix for that, but in the mean time I've changed the behavior of the scrolling so you should more clearly see that there are more items. Basically the IP address is further down on the about screen.

**Comment by VividRGBLighting** [comment]
I tried to scroll - OH!
There is nothing to select, so the wheel doesn't do anything!
I'd have to physically touch-drag the screen!

Again - this is where a user that hasn't touched the system in a year might forget that.

Option - put a selectable "Close" button at the bottom of the page so that the scrolling the wheel jumps the screen?

**Comment by HakanL** [comment]
You can still use the wheel, if you upgrade to the latest release ;) There was a bug.
