### ISSUE TITLE
"Add" me to a list of users so I can attach labels to issues

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#16]
For some reason I can't tag my issues with labels.
Not sure if you have to join me to the project or if I need change a setting somewhere?

But it would be helpful for me to be able to flag bugs vs features vs enhancements.

**Comment by VividRGBLighting** [comment]
And we should add/ make a distinction between a core needed function/feature vs a "nice to have" feature.

Some of these items need to be focused on now and some are really for us while testing.

**Comment by HakanL** [comment]
Done, please confirm that you have access.

**Comment by VividRGBLighting** [comment]
Yes! I had to accept your invitation!
