### ISSUE TITLE
Admin status

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#17]
Two thoughts here,

1> It is not clear that you are in Admin mode vs not Admin mode. Yes the taskbar turns red, but after while, it becomes part of the UI and the Admin mode vs non-admin mode is forgotten. I might suggest that when in Admin Mode the Admin Icon stays visible.
I would also highlight it, like bright red. Or something that is crystal clear that you are in a mode.

2> Provide an automatic Admin Logout timer - after x minutes - like 5 or 10 - which might still be too long once the unit is installed and running.

3> Have a user option that puts the unit in admin mode all the time. This is a toss-up of an idea. And really is only important if you add the 2> time out feature - which would end up being a PITA when in development testing.

**Comment by HakanL** [comment]
Good suggestions. I've changed how it's displayed now, let me know what you think.

**Comment by HakanL** [comment]
Auto logoff and auto-login is implemented now.
