### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#18]
Two items here:

1> DMX Core 100:
      a> Contact info to DMX Pro Sales for support
      b> If the unit connected to the internet, perhaps you can have a "Call me" function where a user can enter their phone number and you can call them? (Advanced feature)

2> Designer / Programmer:
        You will most likely want the user to want to contact the person who programmed the system first, so before they contact you, maybe there should be a first page "contact help" and as a subpage of that page, that includes the #1 info above.

In this day and age, the thing that will put you above everyone else is getting support when they need it.
That is why Vivid puts our phone number on everything. 
You are at a different scale than us, which is why I suggested the call me feature.

**Comment by HakanL** [comment]
I've added a Help screen with contact info for installer, and for DMX Pro Sales (QR code that currently takes the user to the documentation site).
