### ISSUE TITLE
Name update

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#19]
I thought of this the other day...

DMX Core is an odd name for a device that is Ethernet based at its "core".

We might want to explore other names that address the real playback power + interface of the unit.

DMX doesn't immediately indicate that the unit is ethernet capable. 

If the "Core" name is part of the world of possible devices, then maybe it needs a family of device names.

SA Touch Core 40 - Stand Alone Touch screen 40 universe
TouchCore 40
WB Touch40 - Wall Box Touch screen 40 universe.

Just some thoughts to help with marketing.
Not that I don't like the DMX Core name.

Maybe the device is 
WB Touch40 - Powered by DMX Core software?

**Comment by HakanL** [comment]
I appreciate the comment, but in my experience DMX is associated with light control by a lot of customers, plus the domain name was available (and I've applied for a trademark using DMX Core). The wall controller could be named something else, I just started with using numbers in the model name, to not have to try to come up with names :)
