### ISSUE TITLE
DMX output always on

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#4]
System option to always send DMX data.
Possibly also report/display DMX timings - if they are fixed, or be able to set them (advanced feature).

Copied from email:
DMX:
1>Always On, 
2>All DMX to 0 on idol, (not sure why anyone would need this, but if you are going to build a function, build all the options).
3>Stop DMX data after idol x seconds 
4>DMX outputs off.

Option 3 - possibly useful if merging DMX data.

**Comment by HakanL** [comment]
At the moment the DMX timings are fixed (DMX function in the daughter-board firmware), though it may be possible to make some tweaks if necessary. It should be in the middle of the DMX512 spec though. Changing the update frequency may be easier though, but almost everything in the code for the DMX Core itself is built around 40 Hz.

**Comment by HakanL** [comment]
Changed so the output is always on once something has been sent to it. It can be stopped under the Utilities menu.
