### ISSUE TITLE
Software Update Feedback

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#7]
Do not automatically update to new software without user notification.
Possibly require user confirmation before updating.

**Comment by HakanL** [comment]
It's an option that's already there (but not visible in the UI), I just have it set to auto-update on your unit. I can change it.

**Comment by VividRGBLighting** [comment]
I think I misunderstood the way it worked
I thought the list of updates was the already INSTALLED updates - but just now I realized that I have to select and tell it to update.

To that end, the update page should display the currently installed as a reference while you are on the update page.

Which means that the restart I experienced earlier today might not have been a update but a glitch.

**Comment by HakanL** [comment]
The list of updates is what's available (in the cloud), and you can select to install any of them. But I had your device configured to always immediately install any new release. The update page shows a star next to the currently running release. Once you manually select a release then your device is locked into that version and won't auto-update (until I change it in the central admin tool). I don't see that devices will always immediately update, but I have it turned on default now in the beginning so they will always get the latest.

**Comment by VividRGBLighting** [comment]
This is a graphical feedback issue - the fonts are small and the "star" wasn't **immediately** clear when quickly looking at the screen.

**Comment by VividRGBLighting** [comment]
The star should be replaced with "Installed" - as the meaning of the star is not immediately clear to a user.
If the star is the first item in the list, as it is when I look now, after updating, it would mean to me, that this is the most recent version, not the version is installed.

I also think that you need to introduce color - lots of color to report feedback.

**Comment by HakanL** [comment]
I've updated that screen now.
