### ISSUE TITLE
sACN set to receive / input only

### ISSUE THREAD

**Issue by VividRGBLighting** [DMXCore/DmxCore100#8]
In applications where the sACN is not being used to control fixtures, but it is being used to record data, there needs to be a setting so that the recorded shows do NOT get played back over the ethernet port (when the unit is being used as DMX output only).

This would be helpful when connecting to networks that might not be happy with being flooded with sACN packets.

Further discussion is needed here.

**Comment by HakanL** [comment]
Valid comment, I need to think about that a little. You can actually disable an output (Port) and still use it as recording input, but it's not very intuitive.

**Comment by VividRGBLighting** [comment]
I think using the word "PORT" is confusing here.
I know what you mean, but most people won't.

There needs to be a way to indicate what a port is.

I'm also leaning toward the idea that the DMX settings and the ethernet settings might want to be split into two different pages.
Call things by what they are - the open-ended, "it can do whatever you want/need" concept only works if you know what you need to do. Most users are not sure.
I think as things get more powerful, you need to guide the user more directly.
DMX settings
sACN settings

I might even go so far as to split out sACN receive settings and sACN output settings.

Port settings is too ambiguous to someone that doesn't code or understand network packets and sockets etc.

**Comment by HakanL** [comment]
Yeah, initially I had named it "Output Settings", but since it's also used for input I changed it to Port, but I agree that it's too generic. I basically want to use a term for "light connectivity", be it ArtNet, sACN or DMX ports, no matter if it's input or output.

**Comment by HakanL** [comment]
I've made some changes now, so the "port" isn't used when recording. I've pushed an update if you want to take a look, rev139.
